#! /usr/bin/env bash
#
# TODO: rename this script to starter or actuator with suffix a vscode or a code
# Usage this script:
# $ code profile
# where profile is a programming language or a stack and etc.
# Without specifying profile, the script runs Default profile

# checking script arguments
if [[ $# -gt 1 ]]; then
  echo "For now, one argument is enough."
  exit 1
fi

# if [[ "$1" = "" ]]; then
if [[ $# -eq 0 ]]; then
  PROFILE="Default"
  echo -n "Warning: VSCode will run with the Default profile!"
  echo
else
  PROFILE="$1"
fi

WORKSPACE="."
DEBUG="debug"

#DRIVE="/import/storage"
#BASE_DIR="backup_by_mans"
# BASE="/import/storage/backup_by_mans"
BASE="/home/technocrat"
CODE_WORK_DIR="$BASE/code-insiders-data"
CODE_WORK_DATA_DIR="$CODE_WORK_DIR/common"
CODE_WORK_EXTENSIONS_DIR="$CODE_WORK_DIR/extensions"
CODE_BIN_FILE="/opt/visual-studio-code-insiders/bin/code-insiders"

# https://wiki.archlinux.org/title/Visual_Studio_Code#Unable_to_move_items_to_trash
#export ELECTRON_TRASH=trash-cli

# TODO: move this block to the launch area of the JS profile
# export NODE_ENV=production
# export BABEL_ENV=production
# export NODE_ENV=development
# export BABEL_ENV=development
# export ESLINT_NO_DEV_ERRORS=true
# export DISABLE_ESLINT_PLUGIN=true

# Extension sets

# TODO: rename:
# set_* to set_exts_*,
# combo_* to combo_sets_*,
# combos to combo_list or combinations or combos. Done to combos

declare -a set_common=(
  ms-dotnettools.vscode-dotnet-runtime
  VisualStudioExptTeam.vscodeintellicode
  VisualStudioExptTeam.vscodeintellicode-insiders
  VisualStudioExptTeam.vscodeintellicode-completions
  VisualStudioExptTeam.intellicode-api-usage-examples
)

# https://habr.com/ru/articles/583320/
declare -a set_bash=(
  #timonwong.shellcheck
  #rogalmic.bash-debug
  #foxundermoon.shell-format
  mads-hartmann.bash-ide-vscode
  #tetradresearch.vscode-h2o
  meronz.manpages
  Remisa.shellman
  # formulahendry.code-runner # already exists in utilities
  # exiasr.hadolint # move to set_docker
  # jeff-hykin.better-dockerfile-syntax # move to set_docker
  xshrim.txt-syntax
  #woozy-masta.shell-script-ide # Bundle all previous extinsions
  jeff-hykin.better-shellscript-syntax
  # Switch to the Dark+ theme
  # or
  # XD Theme
  liviuschera.noctis # Noctis
  # Kary Pro Colors
  # Material Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
  # Default Theme Enhanced
)

declare -a set_pascal=(
  #alefragnani.pascal
  Wosi.omnipascal
  CNOC.fpdebug
  alefragnani.pascal-formatter
  #webfreak.debug #?
  #coolchyni.beyond-debug
)

declare -a set_c=(
  jeff-hykin.better-c-syntax
)

declare -a set_cpp=(
  # Project generator:
  ACharLuk.fenix
  # or
  danielpinto8zz6.c-cpp-project-generator
  #
  jeff-hykin.better-cpp-syntax
  # jeff-hykin.experimental-cpp-syntax # ?
  # Switch to the Dark+ theme
  # or
  # XD Theme
  liviuschera.noctis # Noctis
  # Kary Pro Colors
  # Material Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
  # Default Theme Enhanced
  #
  ms-vscode.makefile-tools
  # ms-vscode.cpptools-extension-pack
  # consist of:
  # 1. C/C++ for Visual Studio Code:
  ms-vscode.cpptools
  # 2. C/C++ Extension UI Themes
  ms-vscode.cpptools-themes
  # 3. CMake For VisualStudio Code
  twxs.cmake
  # 4. CMake Tools
  ms-vscode.cmake-tools
  # consist end.
)

declare -a set_platformio=(
  # ms-vscode.cpptools-extension-pack
  # consist of:
  # 1. C/C++ for Visual Studio Code:
  # ms-vscode.cpptools
  # 2. C/C++ Extension UI Themes
  # ms-vscode.cpptools-themes
  # 3. CMake For VisualStudio Code
  # twxs.cmake
  # 4. CMake Tools
  # ms-vscode.cmake-tools
  # consist end.
  #
  # jeff-hykin.better-cpp-syntax
  #
  # Project generator:
  #ACharLuk.fenix
  # or
  #danielpinto8zz6.c-cpp-project-generator
  #
  #ms-vscode.makefile-tools
  platformio.platformio-ide
  ms-vscode.vscode-serial-monitor
)

declare -a set_mcu=()

declare -a set_web_front_end=(
  ecmel.vscode-html-css
  # abusaidm.html-snippets
  Zignd.html-css-class-completion
  # mkaufman.HTMLHint
  pranaygp.vscode-css-peek # deprecated?
  solnurkarim.html-to-css-autocompletion
  mrmlnc.vscode-scss
  # MamadOuologuem.frontone-vscode-scss
  Syler.sass-indented
  # glenn2223.live-sass
  michelemelluso.code-beautifier
  stylelint.vscode-stylelint
  diz.ecsstractor-port
  ritwickdey.LiveServer
  naumovs.color-highlight
  # vincaslt.highlight-matching-tag
  # deque-systems.vscode-axe-linter
  anteprimorac.html-end-tag-labels
  kamikillerto.vscode-linthtml
  # https://medium.com/@arslanijaz/vscode-tailwind-extensions-3c38bb2607fd
  bradlc.vscode-tailwindcss
)

declare -a set_jsts=(
  ms-vscode.vscode-typescript-next
  ms-vscode.js-debug-nightly
  dbaeumer.vscode-eslint
  # capaj.vscode-standardjs-snippets
  # xabikos.JavaScriptSnippets
  mgmcdermott.vscode-language-babel
  humao.rest-client
  lllllllqw.jsdoc
  # ChakrounAnas.turbo-console-log
  #esbenp.prettier-vscode
  #tombonnike.vscode-status-bar-format-toggle
  jeff-hykin.better-js-syntax
  # Switch to the Dark+ theme
  # or
  # XD Theme
  # Noctis
  # Kary Pro Colors
  # Material Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
  # Default Theme Enhanced
)

declare -a set_php=(
  xdebug.php-debug
  bmewburn.vscode-intelephense-client
  zobo.php-intellisense
  neilbrayfield.php-docblocker
  junstyle.php-cs-fixer
  mrmlnc.vscode-apache
  shanoor.vscode-nginx
)

declare -a set_python=(
  # donjayamanne.python-extension-pack
  ms-python.python
  ms-python.vscode-pylance
  ms-toolsai.jupyter
  ms-python.isort
  wholroyd.jinja
  batisteo.vscode-django
  donjayamanne.python-environment-manager
  njpwerner.autodocstring
  KevinRose.vsc-python-indent
)

declare -a set_sql=(
  mtxr.sqltools
  alexcvzz.vscode-sqlite
  mtxr.sqltools-driver-pg
  theumletteam.umlet
)

declare -a set_java=(
  # vscjava.vscode-java-pack
  # consist of:
  redhat.java
  vscjava.vscode-java-debug
  vscjava.vscode-java-test
  vscjava.vscode-maven
  vscjava.vscode-gradle
  vscjava.vscode-java-dependency
)

declare -a set_perl=(
  jeff-hykin.better-perl-syntax
  # Material Theme
  # Noctis
  # XD Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
)

declare -a set_haskell=(
  justusadam.language-haskell
)

declare -a set_lisp=(
  jeff-hykin.better-lisp-syntax
)

declare -a set_rust=(
  # https://open-vsx.org/extension/rust-lang/rust-analyzer
)

declare -a set_go=(
  golang.Go
  jeff-hykin.better-go-syntax
)

declare -a set_nix=(
  jnoortheen.nix-ide
  jeff-hykin.better-nix-syntax
)

declare -a set_prolog=(
  jeff-hykin.better-prolog-syntax
)

declare -a set_objectivec=(
  jeff-hykin.better-objc-syntax
)

declare -a set_objectivecpp=(
  jeff-hykin.better-objcpp-syntax
)

declare -a set_docker=(
  ms-azuretools.vscode-docker
  exiasr.hadolint
  jeff-hykin.better-dockerfile-syntax
  # Material Theme
  # Noctis
  # XD Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
)

declare -a set_remote_development=(
  # MS-vsliveshare.vsliveshare
  # ms-vscode-remote.vscode-remote-extensionpack
  # consist of:
  # ms-vscode-remote.remote-ssh
  # ms-vscode.remote-server
  ms-vscode-remote.remote-containers
  # ms-vscode-remote.remote-wsl
)

declare -a set_debuging=(
  webfreak.debug # Supports both GDB and LLDB.
)

declare -a set_git=(
  # eamodio.gitlens
  # mhutchie.git-graph
  # github.vscode-pull-request-github
  # donjayamanne.githistory
  # huizhou.githd
  codezombiech.gitignore
  # GitHub.remotehub
  # GitHub.codespaces
  # GitHub.copilot
)

declare -a set_path_processing=(
  christian-kohler.path-intellisense
  ionutvmi.path-autocomplete
)

declare -a set_code_formatter=(
  esbenp.prettier-vscode                     # move to JS?
  tombonnike.vscode-status-bar-format-toggle # move to JS?
  EditorConfig.EditorConfig
)

declare -a set_organizing_comments_todos_bookmarks=(
  aaron-bond.better-comments
  Gruntfuggly.todo-tree
  alefragnani.Bookmarks
  # ExodiusStudios.comment-anchors
  # wayou.vscode-todo-highlight
)

declare -a set_code_documentation=(
  # PlantUML +
  # mgiesen.image-comments
  #
  # lllllllqw.jsdoc
  cschlosser.doxdocgen
)

declare -a set_vue=(
  Vue.volar
)

declare -a set_twig=(
  mblode.twig-language-2
)

# Doc Writer Profile Template
# https://code.visualstudio.com/docs/editor/profiles#_doc-writer-profile-template

declare -a set_markdown=(
  yzhang.markdown-all-in-one
  DavidAnson.vscode-markdownlint
  # bierner.markdown-mermaid
  # bierner.markdown-preview-github-styles
  # ChrisChinchilla.vscode-pandoc
  # shd101wyy.markdown-preview-enhanced
  # DougFinke.vscode-pandoc # deprecated
)

declare -a set_json=(
  richie5um2.vscode-sort-json
)

declare -a set_utilities=(
  alefragnani.project-manager
  Tyriar.vscode-terminal-here
  drmerfy.overtype
  # formulahendry.code-runner
  robole.profile-status
  natqe.reload
)

declare -a set_spelling=(
  streetsidesoftware.code-spell-checker
  streetsidesoftware.code-spell-checker-russian
)

declare -a set_themes=(
  teabyii.ayu
  arcticicestudio.nord-visual-studio-code
  # ahmadawais.shades-of-purple
  # johnpapa.vscode-peacock
)

declare -a set_icons=(
  # by download rating
  PKief.material-icon-theme # the best
  # vscode-icons-team.vscode-icons
  # equinusocio.vsc-material-theme-icons
  #
  emmanuelbeziat.vscode-great-icons
)

# Special purpose themes
# See Semantic Colorization:
# https://devblogs.microsoft.com/cppblog/visual-studio-code-c-c-extension-july-2019-update/#semantic-colorization
# https://marketplace.visualstudio.com/items?itemName=jeff-hykin.better-syntax

declare -a set_better_syntax_themes=(
  # jeff-hykin.xd-theme # optimized for syntax: C++, Dockerfile, Shell, Perl
  # and also: (JS JSX Rust Vue JSON Python Ruby HTML C# CoffeeScript CSS SASS YAML Markdown WASM Cython Toml)
  liviuschera.noctis # supports a lot of languages # the best
  karyfoundation.theme-karyfoundation-themes
  Equinusocio.vsc-material-theme
  azemoh.one-monokai
  johnpapa.winteriscoming
  hedinne.popping-and-locking-vscode
  peaceshi.syntax-highlight
  # ms-vscode.cpptools-themes
)

declare -a set_special_extensions=(
  WakaTime.vscode-wakatime
)

declare -a set_better_syntax=(
  jeff-hykin.better-csv-syntax
)

# Combination of sets (combo)

declare -a combo_common=(
  set_common
  set_docker
  set_remote_development
  set_git
  set_path_processing
  set_code_formatter
  set_organizing_comments_todos_bookmarks
  set_markdown
  set_json
  set_utilities
  set_spelling
  set_themes
  set_icons
  set_special_extensions
  #set_better_syntax
  set_sql
)

declare -a combo_bash=(
  set_bash
)

declare -a combo_pascal=(
  set_pascal
)

declare -a combo_cpp=(
  set_cpp
)

declare -a combo_web_front_end=(
  set_web_front_end
  set_jsts
)

declare -a combo_jsts=(
  set_jsts
)

declare -a combo_python=(
  set_python
)

declare -a combo_php=(
  set_php
)

declare -a combo_vue=(
  set_vue
)

declare -a combo_platformio=(
  set_platformio
  set_cpp
)

declare -a combo_haskell=(
  set_haskell
)

declare -a combo_java=(
  set_java
)

declare -a combo_go=(
  set_go
)

# Associative array
# profiles name as keys
# value as a name of a combination of extension sets
# combos=([profile]=combo_profile ...)
# TODO: rename combos to combinations
declare -A combos=(
  [common]=combo_common
  [bash]=combo_bash
  [pascal]=combo_pascal
  [cpp]=combo_cpp
  [web]=combo_web_front_end
  [jsts]=combo_jsts
  [python]=combo_python
  [php]=combo_php
  [vue]=combo_vue
  [platformio]=combo_platformio
  [haskell]=combo_haskell
  [java]=combo_java
  [go]=combo_go
)

# Functions

# function code_launcher {
# local -n opt=$1
# $CODE_BIN_FILE \
# --profile "$PROFILE" \
# --user-data-dir $CODE_WORK_DATA_DIR \
# --extensions-dir $CODE_WORK_EXTENSIONS_DIR \
# "${opt[@]}" \
# "$WORKSPACE"
# return $?
# }
function code_launcher {
  # exit 0
  local -n opt=$1
  $CODE_BIN_FILE \
    --user-data-dir $CODE_WORK_DATA_DIR \
    --extensions-dir $CODE_WORK_EXTENSIONS_DIR \
    "${opt[@]}" \
    "$WORKSPACE"
  return $?
}

function merging_of_arrays {
  local -n array_a=$1
  local -n array_b=$2
  local -n acc=$3
  for element in "${array_a[@]}"; do
    acc+=("$element")
  done
  for element in "${array_b[@]}"; do
    acc+=("$element")
  done
  return 0
}

# Сhecks the existence of a profile.
# Usage:
# just call profile_exists
# Globals:
#   combos - associated array
#   PROFILE - profile name
# Returns:
#   0 - profile configuration exists
#   1 - profile configuration not exists
function profile_exists {
  for key in "${!combos[@]}"; do
    if [[ "$key" == "$PROFILE" ]]; then
      return 0
    fi
  done
  return 1
}

# function get_installed_extensions {
# $CODE_BIN_FILE \
# --profile "$PROFILE" \
# --user-data-dir $CODE_WORK_DATA_DIR \
# --extensions-dir $CODE_WORK_EXTENSIONS_DIR \
# --list-extensions \
# "$WORKSPACE"
# return $?
# }

function get_installed_extensions {
  # exit 0
  $CODE_BIN_FILE \
    --user-data-dir $CODE_WORK_DATA_DIR \
    --extensions-dir $CODE_WORK_EXTENSIONS_DIR \
    --list-extensions \
    "$WORKSPACE"
  return $?
}

function get_list_installed_extensions {
  local -n list=$1
  # local -i return_codes
  # https://www.shellcheck.net/wiki/SC2207
  mapfile -t -O 1 list < <(get_installed_extensions return_codes=$?)
  # return $return_codes
}

# Combines combinations of sets into one array.
# Usage:
# function arg result
# Arguments:
#   arg - array of arrays
#   result - merged arrays
# Outputs:
#   result - merged arrays
# Returns:
#   0
function get_list_profile_extensions {
  local -n array_of_arrays=$1
  local -n joined_array=$2
  local -n array_1
  local array_2_element=""
  for array_1 in "${array_of_arrays[@]}"; do
    # echo "$array_1"
    for array_2_element in "${array_1[@]}"; do
      # echo "$array_2_element"
      joined_array+=("$array_2_element")
    done
  done
  return 0
}

function get_full_list_extensions {
  #local -n array_of_arrays
  local -n combo
  local -n set
  local -n joined_array=$1
  local ext=""
  for combo in "${combos[@]}"; do
    # echo $combo
    for set in "${combo[@]}"; do
      # echo $set
      for ext in "${set[@]}"; do
        # echo "${ext}"
        joined_array+=("${ext}")
      done
    done
  done
  # echo "${joined_array[@]}"
  return 0
}

# Name:
# create_a_list_of_parameters
# Usage:
# function argument1 argument2 result
# Input:
# argument1 as reference to list
# argument2 as string action type value
# Output:
# returns result a reference list of run options
function create_a_list_of_parameters {
  # Input:
  local -n ref_to_list_of_extensions=$1
  local action=$2
  # Output:
  local -n ref_to_list_of_installation_options=$3
  for extension_name in "${ref_to_list_of_extensions[@]}"; do
    if [[ $action == "install" ]]; then
      ref_to_list_of_installation_options+=(--install-extension)
      ref_to_list_of_installation_options+=("$extension_name")
      ref_to_list_of_installation_options+=(--pre-release)
      # ref_to_list_of_installation_options+=(--force)
      # ref_to_list_of_installation_options+=(--trace-deprecation)
    fi
    if [[ $action == "uninstall" ]]; then
      ref_to_list_of_installation_options+=(--uninstall-extension)
      ref_to_list_of_installation_options+=("$extension_name")
    fi
    if [[ $action == "disable" ]]; then
      ref_to_list_of_installation_options+=(--disable-extension)
      ref_to_list_of_installation_options+=("$extension_name")
    fi
    # if [[ $action == "enable" ]]; then
    # ref_to_list_of_installation_options+=(--enable-extension)
    # ref_to_list_of_installation_options+=("$extension_name")
    # fi
  done
}

# Calculate the difference between two lists.
# Usage:
# function list_1 list_2 difference
# list_1 - list_2 = difference (for install)
# list_2 - list_1 = difference (for remove)
# Arguments:
#   list_1 (demand)
#   list_2 (installed)
#   difference
# Outputs:
#   difference
# Returns:
#   0
function difference_of_list {
  local -n ref_to_list_1=$1
  local -n ref_to_list_2=$2
  local -n ref_to_differences_lists=$3
  local match_flag="no"
  # take the element of the first list
  for element_of_list_1 in "${ref_to_list_1[@]}"; do
    # compare with each element of the second list
    for element_of_list_2 in "${ref_to_list_2[@]}"; do
      if [[ "$element_of_list_1" == "$element_of_list_2" ]]; then
        # echo "$element_of_list_1 = $element_of_list_2"
        match_flag="yes" # fix a match - the element is present in both lists
        break            # finish iterating the second list
      fi
    done
    # if an element from the first list does not match any element from the second list
    if [[ "${match_flag}" == "no" ]]; then
      # add this item to difference list
      ref_to_differences_lists+=("$element_of_list_1")
      # echo "$element_of_list_1"
    fi
    match_flag="no" # reset match flag
  done              # move to the next item from the first list
  return 0
}

# function make_install_and_uninstall_lists {
# local -n required_extensions=$1
# local -n installed_extensions=$2
# local -n list_install=$3
# local -n list_uninstall=$4
# local -n install_size=$5
# local -n uninstall_size=$6
#
# difference_of_list required_extensions installed_extensions list_install
# difference_of_list installed_extensions required_extensions list_uninstall
# install_size=${#list_install[@]}
# uninstall_size=${#list_uninstall[@]}
# }

function print_list() {
  declare -g DEBUG
  if [[ ! -v DEBUG ]]; then
    return 0
  fi
  local -n array=$1
  echo ""
  echo -n "$2"
  echo "(${#array[@]}):"
  # echo "${array[@]}"
  for element in "${!array[@]}"; do
    echo "${array[element]}"
  done
  # echo ""
  return 0
}

# Main

if [ "$PROFILE" = "help" ]; then
  declare -la options=(--help)
  code_launcher options
  exit 0
fi

# If the combination not exists
if ! profile_exists; then
  echo "Ooops! '${PROFILE}' configuration does not exist!"
  #echo ""
  #echo "Specify the profile and corresponding combination of extension sets in the combos array and repeat again."
  exit 1
fi

# Stuff: Necessary, unnecessary

declare -la full_list_extensions=()
declare -la list_installed_extensions=()
declare -la list_profile_extensions=()
declare -la list_extensions_for_install=()
declare -la list_profile_extensions_for_install
declare -la list_extensions_for_uninstall=()
declare -la list_extensions_for_disable=()
declare -la code_launch_parameters=()
declare -la list_common_extensions=()
declare -i number_of_installed_extensions
declare -i number_of_extensions_for_uninstall
declare -i number_of_extensions_for_install
declare -i number_of_extensions_for_disable
declare -i number_of_profile_extensions_for_install
declare -n combo_name="${combos["$PROFILE"]}"
declare -n combo_common_name="${combos["common"]}"
declare action=''

get_list_profile_extensions combo_name list_profile_extensions
get_list_installed_extensions list_installed_extensions
get_full_list_extensions full_list_extensions
get_list_profile_extensions combo_common_name list_common_extensions

print_list full_list_extensions "Full list extensions "
print_list list_installed_extensions "List installed extensions "
print_list list_profile_extensions "List profile extensions "
print_list list_common_extensions 'List common ext '
print_list list_extensions_for_uninstall 'List ext for uninstall '

# удалить лишние расширения
# uninstall extensions
# сравнить список установленных и общий список расширений
difference_of_list list_installed_extensions full_list_extensions list_extensions_for_uninstall
number_of_extensions_for_uninstall=${#list_extensions_for_uninstall[@]}
if [[ $number_of_extensions_for_uninstall -gt 0 ]]; then
  action='uninstall'
  create_a_list_of_parameters list_extensions_for_uninstall $action code_launch_parameters
  print_list code_launch_parameters 'Code run options '
  code_launcher code_launch_parameters
  code_launch_parameters=()
fi

# обновить установленые
number_of_installed_extensions=${#list_installed_extensions[@]}
if [[ $list_installed_extensions -gt 0 ]]; then
  code_launch_parameters=(--update-extensions)
  code_launcher code_launch_parameters
  code_launch_parameters=()
fi

# установить недостающие
# install extensions
# сравнить список установленных и общий список расширений
difference_of_list full_list_extensions list_installed_extensions list_extensions_for_install
print_list list_extensions_for_install 'List ext for install '
number_of_extensions_for_install=${#list_extensions_for_install[@]}
if [[ $number_of_extensions_for_install -gt 0 ]]; then
  action='install'
  create_a_list_of_parameters list_extensions_for_install $action code_launch_parameters
  print_list code_launch_parameters 'Code launch parameters '
  code_launcher code_launch_parameters
  code_launch_parameters=()
fi

# запустить code с выключением ненужных расширений
# объединить список расширений профиля и common
declare -la profile_and_common_lists=()
merging_of_arrays list_profile_extensions list_common_extensions profile_and_common_lists
print_list profile_and_common_lists 'Profile and common lists '
# сравнить общий список расширений и объединённый
difference_of_list full_list_extensions profile_and_common_lists list_extensions_for_disable
# результатом будет список расширений для выключения
number_of_extensions_for_disable=${#list_extensions_for_disable[@]}
if [[ $number_of_extensions_for_disable -gt 0 ]]; then
  action='disable'
  create_a_list_of_parameters list_extensions_for_disable $action code_launch_parameters
  print_list code_launch_parameters 'Code launch parameters '
  code_launcher code_launch_parameters
  code_launch_parameters=()
fi

# make_install_and_uninstall_lists full_list_extensions list_installed_extensions list_extensions_for_install list_extensions_for_uninstall number_of_extensions_for_install number_of_extensions_for_uninstall

# install extensions
# if [[ $number_of_extensions_for_install -gt 0 ]]; then
#   print_list list_extensions_for_install "List extensions install"
#   action='install'
#   create_a_list_of_parameters list_extensions_for_install $action code_launch_parameters
#   print_list code_launch_parameters 'Code launch parameters:'
#   code_launcher code_launch_parameters
#   code_launch_parameters=()
# fi

# disable extensions
# if [[ $number_of_extensions_for_disable -gt 0 ]]; then
# action='disable'
# create_a_list_of_parameters list_extensions_for_disable $action code_launch_parameters
# print_list code_launch_parameters 'Code launch parameters:'
# code_launcher code_launch_parameters
# code_launch_parameters=()
# fi

# enable extensions
# if [[ $number_of_extensions_for_enable -gt 0 ]]; then
# print_list list_extensions_for_enable "List extensions enable"
# action='enable'
# create_a_list_of_parameters list_extensions_for_enable $action code_launch_parameters
# print_list code_launch_parameters 'Code launch parameters:'
# code_launcher code_launch_parameters
# code_launch_parameters=()
# fi

# launch_options
# code_launch_parameters=(--update-extensions)
# code_launcher code_launch_parameters
# code_launch_parameters=()
# code_launcher code_launch_parameters
exit 0
