#! /usr/bin/env bash
#
# TODO: rename this script to starter or actuator with suffix a vscode or a code
# Usage this script:
# $ code profile
# where profile is a programming language or a stack and etc.
# Without specifying profile, the script runs Default profile

# checking script arguments
if [[ $# -gt 1 ]]; then
  echo "For now, one argument is enough."
  exit 1
fi

# if [[ "$1" = "" ]]; then
if [[ $# -eq 0 ]]; then
  PROFILE="Default"
  echo -n "Warning: VSCode will run with the Default profile!"
  echo
else
  PROFILE="$1"
fi

WORKSPACE="."
# DEBUG="debug"

#DRIVE="/import/storage"
#BASE_DIR="backup_by_mans"
# BASE="/import/storage/backup_by_mans"
BASE="/home/technocrat"
CODE_WORK_DIR="$BASE/code-insiders-data"
CODE_WORK_DATA_DIR="$CODE_WORK_DIR/common"
CODE_WORK_EXTENSIONS_DIR="$CODE_WORK_DIR/extensions"
CODE_BIN_FILE="/opt/visual-studio-code-insiders/bin/code-insiders"

# https://wiki.archlinux.org/title/Visual_Studio_Code#Unable_to_move_items_to_trash
#export ELECTRON_TRASH=trash-cli

# TODO: move this block to the launch area of the JS profile
# export NODE_ENV=production
# export BABEL_ENV=production
# export NODE_ENV=development
# export BABEL_ENV=development
# export ESLINT_NO_DEV_ERRORS=true
# export DISABLE_ESLINT_PLUGIN=true

# Extension sets for different tasks

# https://habr.com/ru/articles/583320/
declare -a set_bash=(
  #timonwong.shellcheck
  #rogalmic.bash-debug
  #foxundermoon.shell-format
  mads-hartmann.bash-ide-vscode
  #tetradresearch.vscode-h2o
  meronz.manpages
  Remisa.shellman
  # formulahendry.code-runner # already exists in utilities
  # exiasr.hadolint # move to set_docker
  # jeff-hykin.better-dockerfile-syntax # move to set_docker
  xshrim.txt-syntax
  jeff-hykin.better-shellscript-syntax
  # Switch to the Dark+ theme
  # or
  # XD Theme
  # Noctis
  # Kary Pro Colors
  # Material Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
  # Default Theme Enhanced
  #woozy-masta.shell-script-ide # Bundle all previous extinsions
)

declare -a set_pascal=(
  #alefragnani.pascal
  alefragnani.pascal-formatter
  Wosi.omnipascal
  CNOC.fpdebug
  #webfreak.debug #?
  #coolchyni.beyond-debug
)

declare -a set_cpp=(
  # ms-vscode.cpptools-extension-pack
  # consist of:
  # 1. C/C++ for Visual Studio Code:
  ms-vscode.cpptools
  # 2. C/C++ Extension UI Themes
  ms-vscode.cpptools-themes
  # 3. CMake For VisualStudio Code
  twxs.cmake
  # 4. CMake Tools
  ms-vscode.cmake-tools
  # consist end.
  #
  jeff-hykin.better-cpp-syntax
  #
  # Project generator:
  ACharLuk.fenix
  # or
  danielpinto8zz6.c-cpp-project-generator
  #
  ms-vscode.makefile-tools
)

declare -a set_of_extensions_for_html=(
  ecmel.vscode-html-css
  # abusaidm.html-snippets
  Zignd.html-css-class-completion
  # mkaufman.HTMLHint
  pranaygp.vscode-css-peek # deprecated?
  solnurkarim.html-to-css-autocompletion
  mrmlnc.vscode-scss
  # MamadOuologuem.frontone-vscode-scss
  Syler.sass-indented
  # glenn2223.live-sass
  michelemelluso.code-beautifier
  stylelint.vscode-stylelint
  diz.ecsstractor-port
  ritwickdey.LiveServer
  naumovs.color-highlight
  # vincaslt.highlight-matching-tag
  # deque-systems.vscode-axe-linter
  anteprimorac.html-end-tag-labels
  kamikillerto.vscode-linthtml
)

declare -a set_of_extensions_for_css=(
  # https://medium.com/@arslanijaz/vscode-tailwind-extensions-3c38bb2607fd
  bradlc.vscode-tailwindcss
)

# TODO refactoring: html+css+js this is front-end set (fe vscode profile), just js i.e. node.js this is back-end set (be vscode profile)
declare -a set_js=(
  ms-dotnettools.vscode-dotnet-runtime
  ms-vscode.vscode-typescript-next
  ms-vscode.js-debug-nightly
  visualstudioexptteam.vscodeintellicode-insiders
  VisualStudioExptTeam.vscodeintellicode-completions
  VisualStudioExptTeam.intellicode-api-usage-examples
  dbaeumer.vscode-eslint
  # capaj.vscode-standardjs-snippets
  # xabikos.JavaScriptSnippets
  mgmcdermott.vscode-language-babel
  humao.rest-client
  lllllllqw.jsdoc
  # ChakrounAnas.turbo-console-log
)
# TODO For js add ext for doc generation

declare -a set_of_extensions_for_nodejs=()

declare -a set_of_extensions_for_ts=(
  ms-vscode.vscode-typescript-next
  ms-dotnettools.vscode-dotnet-runtime
  visualstudioexptteam.vscodeintellicode-insiders
  VisualStudioExptTeam.vscodeintellicode-completions
  VisualStudioExptTeam.intellicode-api-usage-examples
)

declare -a set_of_extensions_for_php=(
  xdebug.php-debug
  bmewburn.vscode-intelephense-client
  zobo.php-intellisense
  neilbrayfield.php-docblocker
  junstyle.php-cs-fixer
  mrmlnc.vscode-apache
  shanoor.vscode-nginx
)

declare -a set_of_extensions_for_python=(
  # donjayamanne.python-extension-pack
  ms-python.python
  ms-python.vscode-pylance
  ms-toolsai.jupyter
  ms-python.isort
  wholroyd.jinja
  batisteo.vscode-django
  ms-dotnettools.vscode-dotnet-runtime
  visualstudioexptteam.vscodeintellicode-insiders
  donjayamanne.python-environment-manager
  njpwerner.autodocstring
  KevinRose.vsc-python-indent
  VisualStudioExptTeam.intellicode-api-usage-examples
  VisualStudioExptTeam.vscodeintellicode-completions
)

declare -a set_of_extensions_for_sql=(
  mtxr.sqltools
  mtxr.sqltools-driver-pg
  theumletteam.umlet
)

declare -a set_java=(
  VisualStudioExptTeam.vscodeintellicode
)

declare -a set_of_extensions_for_perl=(
  jeff-hykin.better-perl-syntax
  # Material Theme
  # Noctis
  # XD Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
)

declare -a set_of_extensions_for_haskell=(
  justusadam.language-haskell
)

declare -a set_of_extensions_for_lisp=(
  jeff-hykin.better-lisp-syntax
)

declare -a set_rust=(
  # https://open-vsx.org/extension/rust-lang/rust-analyzer
)

declare -a set_docker=(
  ms-azuretools.vscode-docker
  jeff-hykin.better-dockerfile-syntax
  # Material Theme
  # Noctis
  # XD Theme
  # One Monokai Theme
  # Winteriscoming
  # Popping and Locking
  # Syntax Highlight Theme
  exiasr.hadolint
)

declare -a set_remote_development=(
  ms-vscode-remote.vscode-remote-extensionpack
  # ms-vscode-remote.remote-containers
  # MS-vsliveshare.vsliveshare
  # johnpapa.vscode-peacock
)
declare -a set_of_extensions_for_debuging=(webfreak.debug)

declare -a set_of_extensions_for_git=(
  # eamodio.gitlens
  mhutchie.git-graph
  # github.vscode-pull-request-github
  # donjayamanne.githistory
  # huizhou.githd
  codezombiech.gitignore
  # GitHub.remotehub
  # GitHub.codespaces
  # GitHub.copilot
)

declare -a set_path_processing=(
  christian-kohler.path-intellisense
  ionutvmi.path-autocomplete
)

declare -a set_of_extensions_for_code_formatter=(
  esbenp.prettier-vscode # move to JS
  tombonnike.vscode-status-bar-format-toggle # move to JS
)

declare -a set_organizing_comments_todos_bookmarks=(
  aaron-bond.better-comments
  Gruntfuggly.todo-tree
  alefragnani.Bookmarks
  # ExodiusStudios.comment-anchors
  # wayou.vscode-todo-highlight
)

declare -a set_code_documentation=(
  # PlantUML +
  # mgiesen.image-comments
  #
  # lllllllqw.jsdoc
  cschlosser.doxdocgen
)

declare -a set_of_extensions_for_vue=(Vue.volar)
declare -a set_of_extensions_for_twig=(mblode.twig-language-2)

# Doc Writer Profile Template
# https://code.visualstudio.com/docs/editor/profiles#_doc-writer-profile-template

declare -a set_markdown=(
  yzhang.markdown-all-in-one
  DavidAnson.vscode-markdownlint
  # bierner.markdown-mermaid
  # bierner.markdown-preview-github-styles
  # ChrisChinchilla.vscode-pandoc
  # shd101wyy.markdown-preview-enhanced
  # DougFinke.vscode-pandoc # deprecated
)

declare -a set_of_extensions_for_json=(
  richie5um2.vscode-sort-json
)

declare -a set_arduino=(
  vsciot-vscode.vscode-arduino # deprecated
  ms-vscode.vscode-serial-monitor
  ms-vscode.cpptools #? всё так же, как и для platformio
  # ms-vscode.cpptools-themes
  jeff-hykin.better-cpp-syntax
  # owen-flood.arduino-snippets-plus
  # farhang0393.arduino-class-creator
)

declare -a set_platformio=(
  # ms-vscode.cpptools-extension-pack
  # consist of:
  # 1. C/C++ for Visual Studio Code:
  ms-vscode.cpptools
  # 2. C/C++ Extension UI Themes
  ms-vscode.cpptools-themes
  # 3. CMake For VisualStudio Code
  twxs.cmake
  # 4. CMake Tools
  ms-vscode.cmake-tools
  # consist end.
  #
  jeff-hykin.better-cpp-syntax
  #
  # Project generator:
  #ACharLuk.fenix
  # or
  #danielpinto8zz6.c-cpp-project-generator
  #
  #ms-vscode.makefile-tools
  platformio.platformio-ide
)

declare -a set_of_extensions_for_mcu=()
declare -a set_of_extensions_for_io=()
declare -a set_of_extensions_for_iot=()

declare -a set_utilities=(
  alefragnani.project-manager
  Tyriar.vscode-terminal-here
  drmerfy.overtype
  formulahendry.code-runner
  richie5um2.vscode-sort-json
  robole.profile-status
  natqe.reload
  EditorConfig.EditorConfig
)

declare -a set_spelling=(
  streetsidesoftware.code-spell-checker
  streetsidesoftware.code-spell-checker-russian
)

declare -a set_icons=(
  # by download rating
  PKief.material-icon-theme # the best
  # vscode-icons-team.vscode-icons
  # equinusocio.vsc-material-theme-icons
  #
  emmanuelbeziat.vscode-great-icons
)

declare -a set_themes=(
  teabyii.ayu
  arcticicestudio.nord-visual-studio-code
  # ahmadawais.shades-of-purple
  # johnpapa.vscode-peacock
)

# Special purpose themes
# See Semantic Colorization:
# https://devblogs.microsoft.com/cppblog/visual-studio-code-c-c-extension-july-2019-update/#semantic-colorization

declare -a set_better_syntax=(
  # jeff-hykin.xd-theme # optimized for syntax: C++, Dockerfile, Shell, Perl
  # and also: (JS JSX Rust Vue JSON Python Ruby HTML C# CoffeeScript CSS SASS YAML Markdown WASM Cython Toml)
  liviuschera.noctis # supports a lot of languages # the best and move to base
  karyfoundation.theme-karyfoundation-themes
  Equinusocio.vsc-material-theme
  azemoh.one-monokai
  johnpapa.winteriscoming
  hedinne.popping-and-locking-vscode
  peaceshi.syntax-highlight
)

declare -a set_special_extensions=(
  WakaTime.vscode-wakatime
)

declare -a set_go=(
  golang.Go
)

# Combination of sets (combo)

declare -a combo_default=(
  set_utilities
  set_themes
  set_icons
  set_spelling
)

declare -a combo_bash=(
  set_utilities
  set_themes
  set_icons
  set_bash
  set_spelling
  set_path_processing
  set_markdown
  set_better_syntax
  set_organizing_comments_todos_bookmarks
  set_special_extensions
  # set_remote_development
)

declare -a combo_pascal=(
  set_utilities
  set_themes
  set_icons
  set_pascal
  set_spelling
  set_path_processing
  set_markdown
  set_better_syntax
  set_organizing_comments_todos_bookmarks
  set_special_extensions
)

declare -a combo_cpp=(
  set_utilities
  set_themes
  set_icons
  set_cpp
  set_spelling
  set_path_processing
  set_markdown
  set_better_syntax
  set_organizing_comments_todos_bookmarks
  set_special_extensions
)

declare -a combination_of_sets_for_markdown=(
  set_utilities
  set_themes
  set_icons
  set_spelling
  set_markdown
  set_better_syntax
  set_special_extensions
)

declare -a combination_of_sets_for_html=(
  set_of_extensions_for_html
  set_markdown
  set_organizing_comments_todos_bookmarks
  #set_better_syntax
  set_path_processing
  set_of_extensions_for_code_formatter
  #set_icons
  set_of_extensions_for_css
)

declare -a combo_js=(
  set_utilities
  set_themes
  set_icons
  set_js
  set_spelling
  set_path_processing
  set_markdown
  set_better_syntax
  set_remote_development
  set_docker
  set_of_extensions_for_html
  set_organizing_comments_todos_bookmarks
  set_special_extensions
  set_of_extensions_for_code_formatter
)

declare -a combination_of_sets_for_python=(
  set_basic
  set_remote_development
  set_docker
  set_markdown
  set_path_processing
  set_of_extensions_for_python
  set_organizing_comments_todos_bookmarks
  #set_better_syntax
  # set_code_documentation
)

declare -a combination_of_sets_for_php=()
declare -a combination_of_sets_for_vue=()

declare -a combination_of_sets_for_sql=(mtxr.sqltools)

declare -a combination_of_sets_for_docker=()
declare -a combination_of_sets_for_remote=()
declare -a combination_of_sets_for_git=(
  set_basic
  set_markdown
  set_of_extensions_for_git
  # set_path_processing
)

declare -a combination_of_sets_for_arduino=(
  set_basic
  set_markdown
  set_path_processing
  set_arduino
  #set_better_syntax
  set_organizing_comments_todos_bookmarks
  set_code_documentation
  #set_icons
)

declare -a combo_platformio=(
  set_utilities
  set_themes
  set_icons
  set_platformio
  # set_cpp
  set_spelling
  set_path_processing
  set_markdown
  set_better_syntax
  set_organizing_comments_todos_bookmarks
  set_special_extensions
  set_code_documentation
)

declare -a combination_of_sets_for_haskell=(
  set_basic
  set_markdown
  set_of_extensions_for_haskell
)

declare -a combo_java=(
  set_utilities
  set_themes
  set_icons
  set_java
  set_spelling
  set_path_processing
  set_markdown
  set_better_syntax
  set_organizing_comments_todos_bookmarks
  set_special_extensions
)

declare -a combo_go=(
  set_utilities
  set_themes
  set_icons
  set_go
  set_spelling
  set_path_processing
  set_markdown
  set_better_syntax
  set_organizing_comments_todos_bookmarks
  set_special_extensions
)

# Associative array
# profiles name as keys
# value as a name of a combination of extension sets
# list_of_combinations=([profile]=combination_of_sets_for_profile ...)
# TODO: rename list_of_combinations to combinations
declare -A list_of_combinations=(
  [Default]=combo_default
  [markdown]=combination_of_sets_for_markdown
  [pascal]=combo_pascal
  [html]=combination_of_sets_for_html
  [js]=combo_js
  [python]=combination_of_sets_for_python
  [php]=combination_of_sets_for_php
  [vue]=combination_of_sets_for_vue
  [cpp]=combo_cpp
  [sql]=combination_of_sets_for_sql
  [bash]=combo_bash
  [docker]=combination_of_sets_for_docker
  [remote]=combination_of_sets_for_remote
  [git]=combination_of_sets_for_git
  [arduino]=combination_of_sets_for_arduino
  [platformio]=combo_platformio
  [haskell]=combination_of_sets_for_haskell
  [java]=combo_java
  [go]=combo_go
)

# Functions

# Сhecks the existence of a profile.
# Usage:
# function arg
# Globals:
#   list_of_combinations - associated array
#   PROFILE - profile name
# Arguments:
#   arg - string as profile name
# Returns:
#   0 - profile configuration exists
#   1 - profile configuration not exists
function profile_is {
  for key in "${!list_of_combinations[@]}"; do
    if [[ $key -eq "$PROFILE" ]];
    then
      return 0
    else
    	return 1
    fi
  done
}

function code_launcher {
  # exit 0
  local -n options=$1
  $CODE_BIN_FILE \
  --profile "$PROFILE" \
  --user-data-dir $CODE_WORK_DATA_DIR \
  --extensions-dir $CODE_WORK_EXTENSIONS_DIR \
  "${options[@]}" \
  "$WORKSPACE"
  return $?
}

function get_installed_extensions {
  # exit 0
  $CODE_BIN_FILE \
  --profile "$PROFILE" \
  --user-data-dir $CODE_WORK_DATA_DIR \
  --extensions-dir $CODE_WORK_EXTENSIONS_DIR \
  --list-extensions \
  "$WORKSPACE"
  return $?
}

function get_list_installed_extensions {
  local -i return_codes
  local -n list_installed_extensions=$1
  # https://www.shellcheck.net/wiki/SC2207
  mapfile -t -O 1 list_installed_extensions < <(get_installed_extensions return_codes=$?)
  return $return_codes
}

# Combines combinations of sets into one array.
# Usage:
# function arg result
# Arguments:
#   arg - array of arrays
#   result - merged arrays
# Outputs:
#   result - merged arrays
# Returns:
#   0
function merge_combo_sets_into_list_extensions {
  local -n array_of_arrays=$1
  local -n merged_array=$2
  local -n array_1
  local array_2=""
  for array_1 in "${array_of_arrays[@]}"; do
    # echo "$array_1"
    for array_2 in "${array_1[@]}"; do
      # echo "$array_2"
      merged_array+=( "$array_2" )
    done
  done
  return 0
}

# Name:
# create_a_list_of_parameters
# Usage:
# function argument1 argument2 result
# Input:
# argument1 as reference to list
# argument2 as string action type value
# Output:
# returns result a reference list of run options
function create_a_list_of_parameters {
  # Input:
  local -n ref_to_list_of_extensions=$1
  local action=$2
  # Output:
  local -n ref_to_list_of_installation_options=$3
  for extension_name in "${ref_to_list_of_extensions[@]}"; do
    if [[ $action == "install" ]]; then
      ref_to_list_of_installation_options+=(--install-extension)
      ref_to_list_of_installation_options+=("$extension_name")
      ref_to_list_of_installation_options+=(--pre-release)
      # ref_to_list_of_installation_options+=(--force)
      # ref_to_list_of_installation_options+=(--trace-deprecation)
    elif [[ $action == "uninstall" ]]; then
      ref_to_list_of_installation_options+=(--uninstall-extension)
    ref_to_list_of_installation_options+=("$extension_name")
    fi
  done
}

# Calculate the difference between two lists.
# Usage:
# function list_1 list_2 difference
# list_1 - list_2 = difference (for install)
# list_2 - list_1 = difference (for remove)
# Arguments:
#   list_1 (demand)
#   list_2 (installed)
#   difference
# Outputs:
#   difference
# Returns:
#   0
function difference_of_list {
  local -n ref_to_list_1=$1
  local -n ref_to_list_2=$2
  local -n ref_to_differences_lists=$3
  local match_flag="no"
  # take the element of the first list
  for element_of_list_1 in "${ref_to_list_1[@]}"; do
    # compare with each element of the second list
    for element_of_list_2 in "${ref_to_list_2[@]}"; do
      if [[ "$element_of_list_1" == "$element_of_list_2" ]]; then
        # echo "$element_of_list_1 = $element_of_list_2"
        match_flag="yes" # fix a match - the element is present in both lists
        break # finish iterating the second list
      fi
    done
    # if an element from the first list does not match any element from the second list
    if [[ "${match_flag}" == "no" ]]; then
      # add this item to difference list
      ref_to_differences_lists+=("$element_of_list_1")
      # echo "$element_of_list_1"
    fi
    match_flag="no" # reset match flag
  done # move to the next item from the first list
  return 0
}

function make_install_and_uninstall_lists {
  local -n required_extensions=$1
  local -n installed_extensions=$2
  local -n list_install=$3
  local -n list_uninstall=$4
  local -n install_size=$5
  local -n uninstall_size=$6

  difference_of_list required_extensions installed_extensions list_install
  difference_of_list installed_extensions required_extensions list_uninstall
  install_size=${#list_install[@]}
  uninstall_size=${#list_uninstall[@]}
}

function print_list() {
  declare -g DEBUG
  if [[ ! -v DEBUG ]]; then
    return 0
  fi
  local -n array=$1
  echo ""
  echo -n "$2"
  echo "(${#array[@]}):"
  # echo "${array[@]}"
  for element in "${!array[@]}"; do
    echo "${array[element]}"
  done
  # echo ""
  return 0
}

if [ "$PROFILE" = "help" ]; then
  declare -la options=(--help)
  code_launcher options
  exit 0
fi

# If the combination exists
if ! profile_is; then
  echo "Ooops! '${PROFILE}' configuration does not exist!"
  echo ""
  echo "Specify the profile and corresponding combination of extension sets in the list_of_combinations array and repeat again."
  exit 1
fi

# List of extensions included in the combination for a specific profile
declare -la list_required_extensions_profile=()
declare -n profile_name="${list_of_combinations["$PROFILE"]}"
# make_list_required_extensions list_required_extensions_profile
merge_combo_sets_into_list_extensions profile_name list_required_extensions_profile
print_list list_required_extensions_profile "Extensions required by profile"

# List of installed extensions
declare -la list_of_installed_extensions=()
get_list_installed_extensions list_of_installed_extensions
print_list list_of_installed_extensions "Extensions already installed"

declare -la list_extensions_install=()
declare -la list_extensions_uninstall=()
declare -la code_run_options=()
declare -i list_extensions_install_size
declare -i list_extensions_uninstall_size
declare action=''
make_install_and_uninstall_lists list_required_extensions_profile list_of_installed_extensions list_extensions_install list_extensions_uninstall list_extensions_install_size list_extensions_uninstall_size

if [[ $list_extensions_uninstall_size -gt 0 ]]; then
  # remove extensions
  print_list list_extensions_uninstall "List extensions uninstall"
  action='uninstall'
  create_a_list_of_parameters list_extensions_uninstall $action code_run_options
  print_list code_run_options 'Code run options'
  code_launcher code_run_options
  code_run_options=()
fi
if [[ $list_extensions_install_size -gt 0 ]]; then
  # install extensions
  print_list list_extensions_install "List extensions install"
  action='install'
  create_a_list_of_parameters list_extensions_install $action code_run_options
  print_list code_run_options 'Code run options'
  code_launcher code_run_options
  code_run_options=()
fi

code_run_options=( --update-extensions )
code_launcher code_run_options
code_run_options=()
code_launcher code_run_options
exit 0
