#!/bin/bash

#
# license ...
#

# Usage this script:
# code language profile
# where language is a programming language or a stack and etc.
# Without specifying profile, the script runs with common set extensions only.

# set -x # Print commands and their arguments as they are executed.
# set -e # Exit immediately if a command exits with a non-zero status.
# But it's considered bad practice, better:
# trap 'do_something' ERR

# https://wiki.archlinux.org/title/Visual_Studio_Code#Unable_to_move_items_to_trash
#export ELECTRON_TRASH=trash-cli

# Created by argbash-init v2.10.0
# ARG_POSITIONAL_SINGLE([language])
# ARG_POSITIONAL_SINGLE([profile])
# ARG_DEFAULTS_POS()
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

# # When called, the process ends.
# Args:
# 	$1: The exit message (print to stderr)
# 	$2: The exit code (default is 1)
# if env var _PRINT_HELP is set to 'yes', the usage is print to stderr (prior to $1)
# Example:
# 	test -f "$_arg_infile" || _PRINT_HELP=yes die "Can't continue, have to supply file as an argument, got '$_arg_infile'" 4
die() {
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}

# Function that evaluates whether a value passed to it begins by a character
# that is a short option of an argument the script knows about.
# This is required in order to support getopts-like short options grouping.
#begins_with_short_option() {
#	local first_option all_short_options='h'
#	first_option="${1:0:1}"
#	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
#}

# THE DEFAULTS INITIALIZATION - POSITIONALS
# The positional args array has to be reset before the parsing, because it may already be defined
# - for example if this script is sourced by an argbash-powered script.
_positionals=()
_arg_language=
_arg_profile=
# THE DEFAULTS INITIALIZATION - OPTIONALS

# Function that prints general usage of the script.
# function get_installed_extensions {
# $CODE_BIN_FILE \
# --profile "$LANGUAGE" \
# --user-data-dir $CODE_WORK_DATA_DIR \
# --extensions-dir $CODE_WORK_EXTENSIONS_DIR \
# --list-extensions \
# "$WORKSPACE"
# return $?
# }
# This is useful if users asks for it, or if there is an argument parsing error (unexpected / spurious arguments)
# and it makes sense to remind the user how the script is supposed to be called.
print_help() {
	printf '%s\n' "<The general help message of my script>"
	printf 'Usage: %s [-h|--help] <language> <profile>\n' "$0"
	printf '\t%s\n' "-h, --help: Prints help"
}

# The parsing of the command-line
parse_commandline() {
	_positionals_count=0
	while test $# -gt 0; do
		_key="$1"
		case "$_key" in
		# The help argurment doesn't accept a value,
		# we expect the --help or -h, so we watch for them.
		-h | --help)
			print_help
			exit 0
			;;
		# We support getopts-style short arguments clustering,
		# so as -h doesn't accept value, other short options may be appended to it, so we watch for -h*.
		# After stripping the leading -h from the argument, we have to make sure
		# that the first character that follows coresponds to a short option.
		-h*)
			print_help
			exit 0
			;;
		*)
			_last_positional="$1"
			_positionals+=("$_last_positional")
			_positionals_count=$((_positionals_count + 1))
			;;
		esac
		shift
	done
}

# Check that we receive expected amount positional arguments.
# Return 0 if everything is OK, 1 if we have too little arguments
# and 2 if we have too much arguments
handle_passed_args_count() {
	local _required_args_string="'language' and 'profile'"
	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}

# Take arguments that we have received, and save them in variables of given names.
# The 'eval' command is needed as the name of target variable is saved into another variable.
assign_positional_args() {
	local _positional_name _shift_for=$1
	# We have an array of variables to which we want to save positional args values.
	# This array is able to hold array elements as targets.
	# As variables don't contain spaces, they may be held in space-separated string.
	_positional_names="_arg_language _arg_profile "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}; do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

# Now call all the functions defined above that are needed to get the job done
parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# vvv  PLACE YOUR CODE HERE  vvv
# For example:
# printf "Value of '%s': %s\\n" 'language' "$_arg_language"
# printf "Value of '%s': %s\\n" 'profile' "$_arg_profile"

## Text colors
#echo -e "\033[31mThis text is red\033[0m"
#echo -e "\033[32mThis text is green\033[0m"
#echo -e "\033[33mThis text is yellow\033[0m"
#echo -e "\033[34mThis text is blue\033[0m"
#echo -e "\033[35mThis text is magenta\033[0m"
#echo -e "\033[36mThis text is cyan\033[0m"
## Reset color at the end with \033[0m to prevent color bleeding

## Define color variables for better readability
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
## Reset color
RESET='\033[0m'

## Using color variables
#echo -e "${RED}This text is red${RESET}"
#echo -e "${GREEN}This text is green${RESET}"
#echo -e "${YELLOW}This text is yellow${RESET}"
#echo -e "${BLUE}This text is blue${RESET}"
#echo -e "${MAGENTA}This text is magenta${RESET}"
#echo -e "${CYAN}This text is cyan${RESET}"

## You can also mix colors in a single line
#echo -e "This is ${RED}red${RESET}, this is ${GREEN}green${RESET}, and this is ${BLUE}blue${RESET}."

## Text styles
BOLD='\033[1m'
UNDERLINE='\033[4m'
## Background colors
BG_RED='\033[41m'
BG_GREEN='\033[42m'
BG_YELLOW='\033[43m'

## Examples with styles
#echo -e "${BOLD}This text is bold${RESET}"
#echo -e "${UNDERLINE}This text is underlined${RESET}"
#echo -e "${RED}${BOLD}This text is bold and red${RESET}"

## Examples with background colors
#echo -e "${BG_RED}This has a red background${RESET}"
#echo -e "${BG_GREEN}${BLUE}Blue text on green background${RESET}"

declare -i DEBUG=1

WORKSPACE="."

LANGUAGE="$_arg_language"

if [[ "$_arg_profile" == "default" ]]; then
	PROFILE="Default"
else
	PROFILE="$_arg_profile"
fi

BASE="$HOME"
CODE_WORK_DIR="$BASE/code-insiders-data"
CODE_WORK_DATA_DIR="$CODE_WORK_DIR/common"
CODE_WORK_EXTENSIONS_DIR="$CODE_WORK_DIR/extensions"
CODE_BIN_FILE="/opt/visual-studio-code-insiders/bin/code-insiders"

PATH_TO="$HOME/.local/share/code_launcher"
# shellcheck source=/dev/null
source "$PATH_TO/code_launcher_db"
# shellcheck source=/dev/null
source "$PATH_TO/code_launcher_api"

if ! exists "$LANGUAGE" combos; then
	echo "Ooops! '$LANGUAGE' configuration does not exist!"
	exit 1 # If the combination not exists
fi

# TODO: show all available setups of launguage

declare -la list_exts_installed
declare -la list_exts_required_base
declare -la list_exts_required_specific
declare -la list_exts_required_all
declare -la list_exts_uninstall
declare -la list_exts_install
declare -la list_exts_full_db

# Main steps:
# 0. Launch the editor
# 1. Get a list of all installed ext's 
# 2. Get a list of all required bease ext's
# 3. Get a list of required ext's for the specific combo
# 4. Merge the base and specific lists of required exs's
# 5. Get the difference between the installed and merged lists (uninstall list)
# 6. Uninstall unnecessary extensions
# 7. Update installed extensions
# 8. Get the difference between the merged and installed lists (install list)
# 9. Install necessary extensions

declare -a run_options=()
#run_options+=("--new-window")
run_options+=()
code_launcher "$WORKSPACE" "$PROFILE" run_options


get_list_exts_for "base" list_exts_required_base
echo -e "${BOLD}${CYAN}Base ext's${RESET}: ${GREEN}$(get_length_array list_exts_required_base)${RESET}"
array_dump list_exts_required_base

if [[ "$LANGUAGE" == "base" ]]; then
	list_exts_required_all=("${list_exts_required_base[@]}")
else
  get_list_exts_for "$LANGUAGE" list_exts_required_specific
  echo "Ext's required for $LANGUAGE: $(get_length_array list_exts_required_specific)"
  array_dump list_exts_required_specific
  merge_arrays list_exts_required_base list_exts_required_specific list_exts_required_all
fi

echo "All required ext's: $(get_length_array list_exts_required_all)"
array_dump list_exts_required_all


get_list_exts_installed "$PROFILE" list_exts_installed
number_installed_exts=$(get_length_array list_exts_installed)

if [[ "$number_installed_exts" -gt 0 ]]; then

  echo "Already installed ext's: $number_installed_exts"
 	array_dump list_exts_installed

  # Make list ext's for uninstal
  compare_lists list_exts_installed list_exts_required_all list_exts_uninstall
  number_exts_to_uninstall=$(get_length_array list_exts_uninstall)
    
  # Uninstall unnecessary extensions
  if [[ $number_exts_to_uninstall -gt 0 ]]; then
    echo "Ext's will be removed: $number_exts_to_uninstall"
	  array_dump list_exts_uninstall
  	uninstall_extensions "$PROFILE" list_exts_uninstall
	else
		echo "No extensions to remove"
  fi
  
	echo ""
  update_extensions "$PROFILE"
  echo "" 
  # Make list ext's for install
  compare_lists list_exts_required_all list_exts_installed list_exts_install

else
	list_exts_install=("${list_exts_required_all[@]}")
fi

number_exts_to_install=$(get_length_array list_exts_install)

# Install necessary extensions
if [[ $number_exts_to_install -gt 0 ]]; then
  echo "Ext's will be installed: $number_exts_to_install"
	array_dump list_exts_install
 	install_extensions "$PROFILE" list_exts_install
else
	echo "No extinsions to install"
	echo ""
fi

get_list_exts_full_db combos list_exts_full_db
echo "List of exts for the entire db: $(get_length_array list_exts_full_db)"
array_dump list_exts_full_db 

case $LANGUAGE in

base)
	echo "This is basic configuration"
	echo ""
	;;

bash)
  echo "Are you ready to write shell scripts. Enjoy!"
	echo ""
	;;

jsts)
  export NODE_ENV=production
  export BABEL_ENV=production
  export NODE_ENV=development
  export BABEL_ENV=development
  export ESLINT_NO_DEV_ERRORS=true
  export DISABLE_ESLINT_PLUGIN=true
  echo "Are you ready to write js and ts scripts. Enjoy!"
  echo ""
	;;

*)
	echo "All right!"
	echo ""
	;;

esac

exit

# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^

# ] <-- needed because of Argbash
